### ISSUE TITLE
TPM should run without the `-b` option

### ISSUE THREAD

**Issue by JBlackCat** [spikegrobstein/linux_desktop_config#1]
The documentation for `tpm` that indicated it should be `run` with the `-b` option was reverted here:

https://github.com/tmux-plugins/tpm/commit/59f78857f656afd462d7bc99b31cc8cc36c1872c

@spikegrobstein

**Comment by spikegrobstein** [comment]
Hey @JBlackCat 

Is tpm being used anywhere in this repo?

**Comment by JBlackCat** [comment]
@spikegrobstein sorry, forgot to link to the code https://github.com/spikegrobstein/linux_desktop_config/blob/master/dotfiles/tmux.conf#L106

**Comment by JBlackCat** [comment]
Closing as the code in question has been removed.
